version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        NPM_CONFIG_LOGLEVEL: warn
    container_name: mern-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/docs:/usr/src/app/docs
      - ./backend/uploads:/usr/src/app/uploads
    environment:
      - PORT=5000
      - SECRET_TOKEN=your_secret_token_here
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - DYNAMODB_ITEMS_TABLE=Items
      - DYNAMODB_ORDERS_TABLE=Orders
      - DYNAMODB_USERS_TABLE=Users
      - NODE_OPTIONS=--max-old-space-size=2048
    networks:
      - mern-app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        CI: "false"
        NPM_CONFIG_LOGLEVEL: warn
    container_name: mern-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - mern-app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mern-app-network:
    driver: bridge

volumes:
  docs:
  uploads: